export const Types = {
  RECIPES_GET_DATA_REQUEST: 'RECIPES_GET_DATA_REQUEST',
  RECIPES_GET_DATA_SUCCESS: 'RECIPES_GET_DATA_SUCCESS',

  FAVOURITE_ADD: 'FAVOURITE_ADD',
  FAVOURITE_REMOVE: 'FAVOURITE_REMOVE',
};
