export const Types = {
  RECIPES_GET_DATA_REQUEST: 'RECIPES_GET_DATA_REQUEST',
  RECIPES_GET_DATA_SUCCESS: 'RECIPES_GET_DATA_SUCCESS',

  FAVOURITES_ADD: 'FAVOURITES_ADD',
  FAVOURITES_REMOVE: 'FAVOURITES_REMOVE',
};
